disabled_rules:
  - trailing_whitespace       # 1394 issues
  - explicit_type_interface   # 1046 issues
  - explicit_acl              #  478 issues
  - sorted_imports            #  116 issues
  - identifier_name           #  101 issues
